---
ID: "3e47e185-1679-4012-8d1f-8d4accb13755"
Parent: "a4d70e7f-2b47-490a-be36-eb5b41a15a83"
Template: "18d0bd79-7da4-4c2a-a924-b93a2b99d669"
Path: /sitecore/content/ironthrone/health/Settings/Shared Sites Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191127T080031Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
