---
ID: "1d95c635-b9d5-43ea-8801-887f72da9f92"
Parent: "e76b91da-e766-4e20-a68c-1279e71af06b"
Template: "e76b91da-e766-4e20-a68c-1279e71af06b"
Path: /sitecore/templates/Project/ironthrone/Partial Design Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {E76B91DA-E766-4E20-A68C-1279E71AF06B}
    {F55D28F4-7479-4F88-80DA-8EBC884A0F7E}
    {C2A8E276-1757-4957-9DD5-8669B79FD80D}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191127T075726Z
