---
ID: "1d1b49de-6448-4533-a013-cb84d382d546"
Parent: "0a421818-2359-4bfe-8eaf-581044baf7f0"
Template: "0a421818-2359-4bfe-8eaf-581044baf7f0"
Path: /sitecore/templates/Project/ironthrone/Site/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {E8E8C94F-4248-43C3-A79F-99FBB49D78E6}
    {45114229-AB93-414D-8B5F-EDE09F9D0ABD}
    {5ECD34F4-B36F-4533-9643-DF41CD8B5036}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191127T075725Z
