---
ID: "b956f287-958f-4414-b4af-5aacefb78582"
Parent: "12f9cbac-28f2-4ca4-ab40-9fcada8fd42f"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/ironthrone/health/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191127T080037Z
