---
ID: "bc6051da-b4e1-4d75-944c-aa5dcde53a88"
Parent: "a016c107-971c-4c16-a871-a6433b58041a"
Template: "a016c107-971c-4c16-a871-a6433b58041a"
Path: /sitecore/templates/Feature/BannerModules/BannerCarousel/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{8F8836D8-D790-4A9F-AAE0-31C8572BA2FE}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111206T102520Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
